# Generated by Django 3.0.4 on 2020-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cookie_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='token',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
